### PR TITLE
Add i18n translation support

### PR DESCRIPTION
**Pull request by starcatter**
#348

Wrapped most user-facing text in i18n.translate().

I intentionally avoided using the available [react components](https://github.com/elastic/kibana/tree/master/packages/kbn-i18n#react) or the [AngularJS wrapper](https://github.com/elastic/kibana/tree/master/packages/kbn-i18n#angularjs) because they do not work for most languages - currently the @kbn/i18n package fully supports [very few languages](https://github.com/elastic/kibana/blob/master/packages/kbn-i18n/src/core/locales.js).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by davidcui1225** [comment]
Thanks for the addition! Looks like the Kibana Reports build is failing, could you also update the jest snapshots with `yarn test -u`?

**Comment by zhongnansu** [comment]
I wonder if this PR only adds support for `pl` (Polish language?)

**Comment by starcatter** [comment]
> Thanks for the addition! Looks like the Kibana Reports build is failing, could you also update the jest snapshots with yarn test -u?

Doing this now. These tests are very helpful, they helped me spot a few places I shouldn't have changed. After I fix that, I'll update the templates to accept some white space changes that make tests fail.

> I wonder if this PR only adds support for `pl` (Polish language?)

Yes, that's what I'm working on. I can move Polish language support to a separate pull request if you would like to keep things clean.

If you mean that it *only* adds support for the Polish language than I don't think it's a problem - it's possible to add translations to a compiled version of Kibana - one has to:
- edit the `.i18nrc.json` file to add the new translation to the plugin
- add a json file with the new translation
- change the locale in `kibana.yml`

There was a (unused and mostly empty) Chinese translation file already there so I also listed it in the `.i18nrc.json`. Should I populate it with English placeholders?

**Comment by zhongnansu** [comment]
Hi Just want to reach out and see if you have a chance to post a PR to our new repo. https://github.com/opensearch-project/dashboards-reports/issues/46 I migated the issues already

Also, I'll merge this PR in this repo if you want @starcatter

**Comment by starcatter** [comment]
> Hi Just want to reach out and see if you have a chance to post a PR to our new repo. [opensearch-project/dashboards-reports#46](https://github.com/opensearch-project/dashboards-reports/issues/46) I migated the issues already

I'll look into that, hopefully setup isn't much harder for opensearch dev environment. 

> Also, I'll merge this PR in this repo if you want @starcatter

Please do. 

If there are any reviewers' remarks regarding my contribution, please let me know, so I can deal with them before transitioning to the opensearch repo.

**Comment by zhongnansu** [comment]
> > Thanks for the addition! Looks like the Kibana Reports build is failing, could you also update the jest snapshots with yarn test -u?
> 
> Doing this now. These tests are very helpful, they helped me spot a few places I shouldn't have changed. After I fix that, I'll update the templates to accept some white space changes that make tests fail.
> 
> > I wonder if this PR only adds support for `pl` (Polish language?)
> 
> Yes, that's what I'm working on. I can move Polish language support to a separate pull request if you would like to keep things clean.
> 
> If you mean that it _only_ adds support for the Polish language than I don't think it's a problem - it's possible to add translations to a compiled version of Kibana - one has to:
> 
> * edit the `.i18nrc.json` file to add the new translation to the plugin
> * add a json file with the new translation
> * change the locale in `kibana.yml`
> 
> There was a (unused and mostly empty) Chinese translation file already there so I also listed it in the `.i18nrc.json`. Should I populate it with English placeholders?

@starcatter The PR looks good to me, thx. One minor thing before we merge this in, could you add a section in README, with instructions on how to add support for another language?

**Review by zhongnansu — APPROVED** [review]

**Review by davidcui1225 — APPROVED** [review]

**Pull request merged**
