### PR TITLE
Fix csv parsing function

### PR DESCRIPTION
**Pull request by joshuali925**
Signed-off-by: Joshua Li <joshuali925@gmail.com>

*Issue #, if available:*
- https://github.com/opensearch-project/dashboards-reports/issues/43
- #363 

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by zhongnansu** [comment]
Can we add test case for this?

**Comment by zhongnansu** [comment]
Why CI is not triggered for this PR

**Comment by joshuali925** [comment]
> Can we add test case for this?

Added. Did we have memory issues with csv reports? I had to flatten the hits to take care of selecting columns like `a.b.c` from `{ 'a.b': { 'c': 'value' } }`, this might increase memory consumption

**Comment by joshuali925** [comment]
https://github.com/joshuali925/kibana-reports/actions check CI here, i think github is having problem with PR triggers

**Comment by zhongnansu** [comment]
> > Can we add test case for this?
> 
> Added. Did we have memory issues with csv reports? I had to flatten the hits to take care of selecting columns like `a.b.c` from `{ 'a.b': { 'c': 'value' } }`, this might increase memory consumption

maybe, like this issue described. https://github.com/opensearch-project/dashboards-reports/issues/34

**Comment by joshuali925** [comment]
> maybe, like this issue described. [opensearch-project/dashboards-reports#34](https://github.com/opensearch-project/dashboards-reports/issues/34)

Got it. I don't think the issue can be resolved by just optimize memory usage while generating csv. We'll have to introduce some kind of external storage for processing data. So this PR shouldn't affect that issue

**Review by zhongnansu — APPROVED** [review]

**Comment by zhongnansu** [comment]
> > maybe, like this issue described. [opensearch-project/dashboards-reports#34](https://github.com/opensearch-project/dashboards-reports/issues/34)
> 
> Got it. I don't think the issue can be resolved by just optimize memory usage while generating csv. We'll have to introduce some kind of external storage for processing data. So this PR shouldn't affect that issue

I think a hard limit on csv file size may be another approach, such as 10 MB

**Comment by zhongnansu** [comment]
can we merge this in? @joshuali925

**Comment by joshuali925** [comment]
missing an approval, @davidcui-amzn could you take a look please?

**Review by davidcui1225 — APPROVED** [review]

**Pull request merged**
